#!/usr/bin/env node
/*
 * Builds the JSON Explorer skill (plugins/json-explorer/skills/json-explorer) from src/:
 *
 *   scripts/json-explorer.mjs   the CLI (src/cli), one readable ES module with no dependencies
 *   assets/viewer.html          the offline viewer (src/viewer), one HTML file with a strict CSP
 *   THIRD_PARTY_NOTICES.txt     licenses of the open-source code bundled into both
 *   references/commands.md      every command's --help, for the skill to read when needed
 *
 * Usage:
 *   node scripts/build-skill.mjs             build
 *   node scripts/build-skill.mjs --check     fail if the committed files are not what the sources build
 *   node scripts/build-skill.mjs --package   build, then write dist/json-explorer.skill (zip for claude.ai)
 *
 * Builds are deterministic: the same sources and dependencies give byte-identical files.
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import zlib from 'node:zlib';
import * as esbuild from 'esbuild';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const PLUGIN_DIR = path.join(ROOT, 'plugins', 'json-explorer');
export const SKILL_DIR = path.join(PLUGIN_DIR, 'skills', 'json-explorer');
export const OUTPUTS = {
  cli: path.join(SKILL_DIR, 'scripts', 'json-explorer.mjs'),
  viewer: path.join(SKILL_DIR, 'assets', 'viewer.html'),
  notices: path.join(SKILL_DIR, 'THIRD_PARTY_NOTICES.txt'),
  commands: path.join(SKILL_DIR, 'references', 'commands.md'),
};
const DATA_MARKER = '/*JSON_EXPLORER_DATA*/';
const TITLE_MARKER = '__JSON_EXPLORER_TITLE__';
const REPOSITORY = 'https://github.com/saiprasaad/JsonExplorer';

function readVersion() {
  const source = fs.readFileSync(path.join(ROOT, 'src', 'cli', 'version.js'), 'utf8');
  const match = /VERSION = '([^']+)'/.exec(source);
  if (!match) throw new Error('src/cli/version.js does not define VERSION.');
  return match[1];
}

/* ─── The CLI ─── */

async function buildCli(version) {
  const result = await esbuild.build({
    absWorkingDir: ROOT,
    entryPoints: ['src/cli/bin.js'],
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node18',
    // jsonc-parser's "main" is a UMD build that loads its modules at run time; use its ES modules.
    mainFields: ['module', 'main'],
    loader: { '.js': 'jsx' },
    legalComments: 'none',
    charset: 'ascii',
    metafile: true,
    write: false,
    outfile: 'json-explorer.mjs',
    logLevel: 'silent',
    banner: {
      js: [
        '#!/usr/bin/env node',
        `// JSON Explorer ${version}: explore, query, diff, validate, repair, format and convert JSON locally.`,
        `// Generated by scripts/build-skill.mjs from src/cli in ${REPOSITORY}. Do not edit.`,
        '// Runs offline: it reads and writes only the files you name and makes no network requests.',
        '// Bundled open-source code and its licenses: ../THIRD_PARTY_NOTICES.txt',
        "import { createRequire as __createRequire } from 'node:module';",
        'const require = __createRequire(import.meta.url);',
      ].join('\n'),
    },
  });
  const [output] = result.outputFiles;
  return { text: output.text, metafile: result.metafile };
}

/* ─── The viewer ─── */

const FAVICON = `data:image/svg+xml,${encodeURIComponent(
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="8" fill="#0f2635"/><g fill="none" stroke="#55c6b8" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M12.5 8.5c-2 0-3 1-3 3v2.2c0 1.2-.8 1.9-2 2.3 1.2.4 2 1.1 2 2.3v2.2c0 2 1 3 3 3"/><path d="M19.5 8.5c2 0 3 1 3 3v2.2c0 1.2.8 1.9 2 2.3-1.2.4-2 1.1-2 2.3v2.2c0 2-1 3-3 3"/></g><circle cx="16" cy="16" r="1.9" fill="#55c6b8"/></svg>'
)}`;

/** The page's Content Security Policy: only the page's own script runs, and nothing loads from anywhere. */
export function contentSecurityPolicy(scriptHash) {
  return [
    "default-src 'none'",
    `script-src '${scriptHash}'`,
    // MUI and React set inline styles; styles cannot load anything, because every URL source is blocked.
    "style-src 'unsafe-inline'",
    'img-src data: blob:',
    'font-src data:',
    "connect-src 'none'",
    "media-src 'none'",
    "object-src 'none'",
    "frame-src 'none'",
    "child-src 'none'",
    "worker-src 'none'",
    "manifest-src 'none'",
    "form-action 'none'",
    "base-uri 'none'",
  ].join('; ');
}

function assertInlineSafe(text, what) {
  // Sequences that would end the element early, or (with "<!--") let a later "<script" change
  // where it ends. esbuild already writes "</script" in strings as "<\/script".
  for (const pattern of [/<\/script/i, /<\/style/i, /<!--/]) {
    if (pattern.test(text)) throw new Error(`The ${what} bundle contains ${pattern}, which cannot be inlined into the page safely.`);
  }
}

async function buildViewer(version) {
  const result = await esbuild.build({
    absWorkingDir: ROOT,
    entryPoints: ['src/viewer/index.jsx'],
    bundle: true,
    minify: true,
    format: 'iife',
    platform: 'browser',
    target: ['chrome111', 'edge111', 'firefox113', 'safari16.4'],
    jsx: 'automatic',
    loader: { '.js': 'jsx' },
    define: { 'process.env.NODE_ENV': '"production"' },
    legalComments: 'none',
    charset: 'ascii',
    metafile: true,
    write: false,
    outdir: 'viewer',
    logLevel: 'silent',
  });
  const script = result.outputFiles.find((file) => file.path.endsWith('.js')).text.trim();
  const style = result.outputFiles.find((file) => file.path.endsWith('.css')).text.trim();
  assertInlineSafe(script, 'viewer script');
  assertInlineSafe(style, 'viewer style');
  // Nothing in the styles may point outside the page (the CSP would block it anyway).
  const external = /url\(\s*(['"]?)(?!data:|#)[^)]*\)|@import/i.exec(style);
  if (external) throw new Error(`The viewer styles reference an external resource: ${external[0]}`);
  const scriptHash = `sha256-${createHash('sha256').update(script, 'utf8').digest('base64')}`;
  const html = [
    '<!doctype html>',
    // translate="no" and notranslate: browser translation would send the page's text to a service.
    '<html lang="en" translate="no">',
    '<head>',
    '<meta charset="utf-8">',
    `<meta http-equiv="Content-Security-Policy" content="${contentSecurityPolicy(scriptHash)}">`,
    '<meta name="referrer" content="no-referrer">',
    '<meta name="google" content="notranslate">',
    '<meta http-equiv="x-dns-prefetch-control" content="off">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    '<meta name="color-scheme" content="dark light">',
    '<meta name="theme-color" content="#0f1d29">',
    `<meta name="generator" content="JSON Explorer ${version}">`,
    `<title>${TITLE_MARKER}</title>`,
    `<link rel="icon" href="${FAVICON}">`,
    `<style>${style}</style>`,
    '</head>',
    '<body>',
    '<noscript><p style="padding:24px;font-family:sans-serif">This page needs JavaScript to show the data. It runs entirely in your browser and makes no network requests.</p></noscript>',
    '<div id="root"></div>',
    `<script type="application/json" id="je-data">${DATA_MARKER}</script>`,
    `<script>${script}</script>`,
    '</body>',
    '</html>',
    '',
  ].join('\n');
  for (const marker of [DATA_MARKER, TITLE_MARKER]) {
    if (html.split(marker).length !== 2) throw new Error(`The viewer page must contain ${marker} exactly once.`);
  }
  return { text: html, metafile: result.metafile, scriptHash };
}

/* ─── Third-party notices ─── */

const LICENSE_FILES = /^(licen[cs]e|copying|notice)(\.(md|txt|markdown))?$/i;

/** The packages (name, version, license text) whose code went into the bundles. */
export function bundledPackages(metafiles) {
  const roots = new Set();
  metafiles.forEach((metafile) =>
    Object.keys(metafile.inputs).forEach((input) => {
      const match = /^(.*node_modules\/(?:@[^/]+\/)?[^/]+)\//.exec(input.replace(/\\/g, '/'));
      if (match) roots.add(match[1]);
    })
  );
  const packages = new Map();
  [...roots].forEach((root) => {
    const directory = path.join(ROOT, root);
    const manifest = JSON.parse(fs.readFileSync(path.join(directory, 'package.json'), 'utf8'));
    const key = `${manifest.name}@${manifest.version}`;
    if (packages.has(key)) return;
    const files = fs
      .readdirSync(directory)
      .filter((file) => LICENSE_FILES.test(file))
      .sort();
    const license = typeof manifest.license === 'string' ? manifest.license : manifest.license?.type ?? 'see the package';
    const texts = files.map((file) => fs.readFileSync(path.join(directory, file), 'utf8').replace(/\r\n/g, '\n').trim());
    packages.set(key, { name: manifest.name, version: manifest.version, license, texts });
  });
  return [...packages.values()].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
}

function buildNotices(metafiles, version) {
  const packages = bundledPackages(metafiles);
  const rule = '-'.repeat(78);
  const sections = packages.map((item) =>
    [
      rule,
      `${item.name} ${item.version} (${item.license})`,
      rule,
      item.texts.length ? item.texts.join('\n\n') : `No license file is included in this package; it is published under the ${item.license} license.`,
    ].join('\n')
  );
  return [
    `JSON Explorer ${version} bundles the following open-source packages into`,
    'scripts/json-explorer.mjs and assets/viewer.html. Their licenses follow.',
    '',
    ...sections.flatMap((section) => [section, '']),
  ].join('\n');
}

/* ─── Command reference ─── */

/** references/commands.md: the built CLI's own --help for every command, so it never drifts. */
function buildCommandReference(cliText) {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'json-explorer-build-'));
  try {
    const script = path.join(directory, 'json-explorer.mjs');
    fs.writeFileSync(script, cliText);
    const help = (...args) => execFileSync(process.execPath, [script, ...args], { encoding: 'utf8', env: { ...process.env, NO_COLOR: '1' } }).trimEnd();
    const overview = help('--help');
    const commands = [...overview.split('Commands:')[1].matchAll(/^ {2}([a-z-]+) {2,}/gm)].map((match) => match[1]);
    return [
      '# JSON Explorer command reference',
      '',
      'The output of `json-explorer <command> --help` for every command. Generated by `scripts/build-skill.mjs`; do not edit.',
      '',
      ...commands.map((command) => `- [${command}](#${command})`),
      '',
      '```text',
      overview,
      '```',
      '',
      ...commands.flatMap((command) => [`## ${command}`, '', '```text', help(command, '--help'), '```', '']),
    ].join('\n');
  } finally {
    fs.rmSync(directory, { recursive: true, force: true });
  }
}

/* ─── Packaging (a zip with the skill folder at the top, as claude.ai expects) ─── */

const CRC_TABLE = Array.from({ length: 256 }, (_, n) => {
  let c = n;
  for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c >>> 0;
});

function crc32(buffer) {
  let crc = 0xffffffff;
  for (const byte of buffer) crc = CRC_TABLE[(crc ^ byte) & 0xff] ^ (crc >>> 8);
  return (crc ^ 0xffffffff) >>> 0;
}

function listFiles(directory, prefix = '') {
  return fs
    .readdirSync(directory, { withFileTypes: true })
    .filter((entry) => !entry.name.startsWith('.') && entry.name !== '__pycache__' && !entry.name.endsWith('.pyc'))
    .sort((a, b) => (a.name < b.name ? -1 : 1))
    .flatMap((entry) => {
      const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
      return entry.isDirectory() ? listFiles(path.join(directory, entry.name), relative) : [relative];
    });
}

/** A deterministic zip (fixed timestamps, sorted entries) of `directory` under the folder name `top`. */
export function zipDirectory(directory, top) {
  const locals = [];
  const centrals = [];
  let offset = 0;
  const dosTime = 0; // 00:00:00
  const dosDate = ((2020 - 1980) << 9) | (1 << 5) | 1; // 2020-01-01
  listFiles(directory).forEach((relative) => {
    const data = fs.readFileSync(path.join(directory, relative));
    const name = Buffer.from(`${top}/${relative}`, 'utf8');
    const compressed = zlib.deflateRawSync(data, { level: 9 });
    const crc = crc32(data);
    const executable = (fs.statSync(path.join(directory, relative)).mode & 0o111) !== 0;
    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4);
    local.writeUInt16LE(0x0800, 6); // UTF-8 names
    local.writeUInt16LE(8, 8); // deflate
    local.writeUInt16LE(dosTime, 10);
    local.writeUInt16LE(dosDate, 12);
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(compressed.length, 18);
    local.writeUInt32LE(data.length, 22);
    local.writeUInt16LE(name.length, 26);
    local.writeUInt16LE(0, 28);
    const central = Buffer.alloc(46);
    central.writeUInt32LE(0x02014b50, 0);
    central.writeUInt16LE((3 << 8) | 20, 4); // made by Unix, so the permissions below apply
    central.writeUInt16LE(20, 6);
    central.writeUInt16LE(0x0800, 8);
    central.writeUInt16LE(8, 10);
    central.writeUInt16LE(dosTime, 12);
    central.writeUInt16LE(dosDate, 14);
    central.writeUInt32LE(crc, 16);
    central.writeUInt32LE(compressed.length, 20);
    central.writeUInt32LE(data.length, 24);
    central.writeUInt16LE(name.length, 28);
    central.writeUInt16LE(0, 30);
    central.writeUInt16LE(0, 32);
    central.writeUInt16LE(0, 34);
    central.writeUInt16LE(0, 36);
    central.writeUInt32LE(((executable ? 0o100755 : 0o100644) << 16) >>> 0, 38);
    central.writeUInt32LE(offset, 42);
    locals.push(local, name, compressed);
    centrals.push(central, name);
    offset += local.length + name.length + compressed.length;
  });
  const directoryBuffer = Buffer.concat(centrals);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(centrals.length / 2, 8);
  end.writeUInt16LE(centrals.length / 2, 10);
  end.writeUInt32LE(directoryBuffer.length, 12);
  end.writeUInt32LE(offset, 16);
  return Buffer.concat([...locals, directoryBuffer, end]);
}

/* ─── Main ─── */

export async function buildAll() {
  const version = readVersion();
  const [cli, viewer] = await Promise.all([buildCli(version), buildViewer(version)]);
  return {
    version,
    scriptHash: viewer.scriptHash,
    files: {
      [OUTPUTS.cli]: cli.text,
      [OUTPUTS.viewer]: viewer.text,
      [OUTPUTS.notices]: buildNotices([cli.metafile, viewer.metafile], version),
      [OUTPUTS.commands]: buildCommandReference(cli.text),
    },
  };
}

async function run(argv) {
  const check = argv.includes('--check');
  const { files, version, scriptHash } = await buildAll();
  const relative = (file) => path.relative(ROOT, file);
  if (check) {
    const stale = Object.entries(files)
      .filter(([file, text]) => !fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== text)
      .map(([file]) => relative(file));
    if (stale.length > 0) {
      console.error(`Out of date: ${stale.join(', ')}. Run: npm run build:skill`);
      return 1;
    }
    console.log('The skill is up to date with its sources.');
    return 0;
  }
  Object.entries(files).forEach(([file, text]) => {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, text);
    console.log(`Wrote ${relative(file)} (${(Buffer.byteLength(text) / 1024).toFixed(0)} KB)`);
  });
  fs.chmodSync(OUTPUTS.cli, 0o755);
  console.log(`Viewer script hash: ${scriptHash}`);
  if (argv.includes('--package')) {
    const target = path.join(ROOT, 'dist', 'json-explorer.skill');
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, zipDirectory(SKILL_DIR, 'json-explorer'));
    console.log(`Wrote ${relative(target)} (JSON Explorer ${version}; upload it in Claude: Settings > Capabilities > Skills)`);
  }
  return 0;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  run(process.argv.slice(2)).then(
    (code) => {
      process.exitCode = code;
    },
    (error) => {
      console.error(error.message);
      process.exitCode = 1;
    }
  );
}
